# Generated by Django 4.2.3 on 2023-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPostApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_attachments/'),
        ),
    ]
